import { tool } from "ai";
import { z } from "zod";
import React from "react";
import { renderToBuffer, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { createAdminClient } from "@/lib/supabase/server";
import { v4 as uuidv4 } from "uuid";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a" },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 16 },
  h1: { fontSize: 15, fontFamily: "Helvetica-Bold", marginTop: 16, marginBottom: 6 },
  h2: { fontSize: 13, fontFamily: "Helvetica-Bold", marginTop: 12, marginBottom: 4 },
  p: { marginBottom: 8, lineHeight: 1.5 },
  bullet: { flexDirection: "row", marginBottom: 4, paddingLeft: 8 },
  bulletDot: { width: 12 },
  bulletText: { flex: 1, lineHeight: 1.5 },
  footer: { position: "absolute", bottom: 24, left: 48, right: 48, fontSize: 8, color: "#888" },
});

// Minimal markdown -> react-pdf block renderer. Supports #/## headings, bullet lists, and paragraphs —
// deliberately not a full markdown engine, just enough for agent-generated report structure.
function renderMarkdownBlocks(markdown: string) {
  const lines = markdown.split("\n");
  const blocks: React.ReactElement[] = [];
  let key = 0;

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith("## ")) {
      blocks.push(React.createElement(Text, { style: styles.h2, key: key++ }, line.slice(3)));
    } else if (line.startsWith("# ")) {
      blocks.push(React.createElement(Text, { style: styles.h1, key: key++ }, line.slice(2)));
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      blocks.push(
        React.createElement(
          View,
          { style: styles.bullet, key: key++ },
          React.createElement(Text, { style: styles.bulletDot }, "•"),
          React.createElement(Text, { style: styles.bulletText }, line.slice(2))
        )
      );
    } else {
      blocks.push(React.createElement(Text, { style: styles.p, key: key++ }, line));
    }
  }
  return blocks;
}

function ReportDocument({ title, markdown }: { title: string; markdown: string }) {
  return React.createElement(
    Document,
    {},
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(Text, { style: styles.title }, title),
      ...renderMarkdownBlocks(markdown),
      React.createElement(
        Text,
        { style: styles.footer, render: ({ pageNumber, totalPages }: any) => `Page ${pageNumber} / ${totalPages} — Generated by MicroManus` },
        ""
      )
    )
  );
}

export function makeCreatePdfReportTool(opts: { userId: string; threadId: string; messageId?: string }) {
  return tool({
    description:
      "Render a markdown report as a polished PDF and upload it to storage. Call this once, near the end of a research task, with the full final report content in markdown.",
    parameters: z.object({
      title: z.string().describe("Report title"),
      markdown_content: z
        .string()
        .describe("Full report body in markdown (headings with # or ##, bullets with -, paragraphs)"),
    }),
    execute: async ({ title, markdown_content }) => {
      const buffer = await renderToBuffer(
        ReportDocument({ title, markdown: markdown_content }) as any
      );

      const admin = createAdminClient();
      const path = `${opts.userId}/${opts.threadId}/${uuidv4()}.pdf`;

      const { error: uploadError } = await admin.storage
        .from("reports")
        .upload(path, buffer, { contentType: "application/pdf", upsert: false });

      if (uploadError) {
        throw new Error(`Failed to upload PDF: ${uploadError.message}`);
      }

      const { data: signed, error: signError } = await admin.storage
        .from("reports")
        .createSignedUrl(path, 60 * 60 * 24 * 7); // 7 days

      if (signError || !signed) {
        throw new Error(`Failed to sign PDF URL: ${signError?.message}`);
      }

      await admin.from("reports").insert({
        thread_id: opts.threadId,
        message_id: opts.messageId ?? null,
        title,
        storage_url: signed.signedUrl,
      });

      return {
        title,
        download_url: signed.signedUrl,
        note: "PDF generated and uploaded. Mention it is available for download in your final answer.",
      };
    },
  });
}
